PROGNAME = cf-agent cf-monitord cf-serverd
PRIORITY = SCHED_PRIORITY_DEFAULT
STACKSIZE = 768

include $(APPDIR)/Application.mk

all::
	$(MAKE) -C core all

install::
	$(MAKE) -C core install

context::
	echo "todo: context target"

depend::
	echo "todo: depend target"
